[program:random-giveaway-api]
command=/root/random-giveaway/venv/bin/uvicorn randomgiveaway.main:app --host 127.0.0.1 --port 8001
directory=/root/random-giveaway
user=root
autostart=true
autorestart=true
startsecs=5
startretries=10
stopsignal=INT
stopwaitsecs=15
stdout_logfile=/var/log/random-giveaway-api.out.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile=/var/log/random-giveaway-api.err.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=5
environment=PYTHONUNBUFFERED="1"
